# These are supported funding model platforms

#github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
#patreon: # Replace with a single Patreon username
#open_collective: # Replace with a single Open Collective username
#ko_fi: # Replace with a single Ko-fi username
#tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
#community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
#liberapay: # Replace with a single Liberapay username
#issuehunt: # Replace with a single IssueHunt username
#otechie: # Replace with a single Otechie username
custom: ['https://checkout.opennode.com/p/ad468614-7111-420d-826f-b3178096e7ba', 'https://checkout.opennode.com/p/7e374ff4-2f5b-4f2e-b1c4-3b3291cd1761','https://locha.io'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
